Document: f24client
Title: Debian f24client Manual
Author: <insert document author here>
Abstract: This manual describes what f24client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/f24client/f24client.sgml.gz

Format: postscript
Files: /usr/share/doc/f24client/f24client.ps.gz

Format: text
Files: /usr/share/doc/f24client/f24client.text.gz

Format: HTML
Index: /usr/share/doc/f24client/html/index.html
Files: /usr/share/doc/f24client/html/*.html
